### ISSUE TITLE
error sql when updating

### ISSUE THREAD

**Issue by GildDart** [UCSCLibrary/SimpleVocabPlus#13]
Hi,

I tried to update SimpleVocabPlus from 2.4 to 3.1.1. 
Omeka Classic 3.0.1 (reclaimhosting.com)

I desactivate the 2.4 plugin and rename it in "_old"
Upload the 3.1.1 and rename it
I am invited to update it and then I get the following error :

`Zend_Db_Statement_Mysqli_Exception
Mysqli statement execute error : Duplicate column name 'type'

Zend_Db_Statement_Mysqli_Exception: Mysqli statement execute error : Duplicate column name 'type' in /home/pierrehe/mysite.org/application/libraries/Zend/Db/Statement/Mysqli.php:215
Stack trace:
#0 /home/pierrehe/mysite.org/application/libraries/Zend/Db/Statement.php(303): Zend_Db_Statement_Mysqli->_execute(Array)
#1 /home/pierrehe/mysite.org/application/libraries/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /home/pierrehe/mysite.org/application/libraries/Omeka/Db.php(80): Zend_Db_Adapter_Abstract->query('ALTER TABLE `om...')
#3 /home/pierrehe/mysite.org/plugins/SimpleVocabPlus/SimpleVocabPlusPlugin.php(94): Omeka_Db->__call('query', Array)
#4 /home/pierrehe/mysite.org/application/libraries/Omeka/Plugin/Broker.php(142): SimpleVocabPlusPlugin->hookUpgrade(Array)
#5 /home/pierrehe/mysite.org/application/libraries/Omeka/Plugin/Installer.php(92): Omeka_Plugin_Broker->callHook('upgrade', Array, Object(Plugin))
#6 /home/pierrehe/mysite.org/application/controllers/PluginsController.php(231): Omeka_Plugin_Installer->upgrade(Object(Plugin))
#7 /home/pierrehe/mysite.org/application/libraries/Zend/Controller/Action.php(516): PluginsController->upgradeAction()
#8 /home/pierrehe/mysite.org/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('upgradeAction')
#9 /home/pierrehe/mysite.org/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#10 /home/pierrehe/mysite.org/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#11 /home/pierrehe/mysite.org/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#12 /home/pierrehe/mysite.org/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#13 /home/pierrehe/mysite.org/admin/index.php(28): Omeka_Application->run()
#14 {main}`

Thanks for your help
Gil

**Comment by DBinaghi** [comment]
Hello, Gil.
I'm afraid you mixed forks, here: 3.1.1 is a fork of mine of the original plugin, whose official version was 2.4.
Nonetheless, thanks for the remark: there was a typo in the code, blocking the upgrade. Now it is solved, a new release will be available soon.
