### ISSUE TITLE
Error  message when attempting to create vocabulary

### ISSUE THREAD

**Issue by janneken** [UCSCLibrary/SimpleVocabPlus#6]
I successfully installed Simple Vocab Plus and am looking forward to using it.  Yet when I attempt to create a new vocabulary, I get an error message from Omeka, disallowing me from creating the vocabulary. Is this a known issue? Any advice?
![omeka error](https://cloud.githubusercontent.com/assets/15268055/13015581/e2324312-d187-11e5-8452-151bbc4a6a8c.jpg)

**Comment by NedHenry** [comment]
Thanks for reporting this. We just recently found this bug ourselves. I will release an updated version to fix this bug soon, either today or early next week. Thank you for using this plugin, and apologies for the error!

**Comment by NedHenry** [comment]
I just committed the fix on this Github project. I have not yet released the new version on the Omeka.org repositories, but will do so early next week after testing it some more.
Thanks for pointing this out! I'm not sure when this bug was introduced.

**Comment by janneken** [comment]
Thank you for looking in to this! I will pay attention for the update. This will no doubt be a great tool as I introduce Dublin Core to students.
