### ISSUE TITLE
Could Simple Vocab Plus read the entries already present in Omeka's repository?

### ISSUE THREAD

**Issue by DBinaghi** [UCSCLibrary/SimpleVocabPlus#9]
Hi.
Many times, errors while entering new data is just a matter of spelling.
Would there be a way to use Simple Vocab Plus, as an option, to read the data already present for a specific field (say, Publisher, or Creator) and use them for the autocomplete function? This way, if for instance "Doe, John" was already present in the repository, when user starts typing "Do" they would see "Doe, John" among the available suggestions.
Thanks for your work.

**Comment by NedHenry** [comment]
This is a good idea that would probably be useful. Here at UCSC we no longer have the developer resources to make substantive upgrades on this plugin, but if anyone else from the community wants to take this on we would fully support that.

**Comment by DBinaghi** [comment]
So, for every field the available options could be:
- no change (just an input field);
- autocomplete input field (with the values already present in the repository);
- autocomplete input field (with the values set in a list defined in Omeka);
- autocomplete input field (with the values taken from list defined in the cloud).
For the last three, an option to allow adding a new value or to choose only from existing ones should be added.
Let's see if anybody could work on it.

**Comment by DBinaghi** [comment]
Right, a newer version (3.0) is available, and I've open a pull request in case you wanted to update yours.
Thanks again for your initial work.
